const { test, expect } = require('@playwright/test');
let app; let page;
test.beforeEach(async () => { app = await require('playwright')._electron.launch({ args: ['.'], cwd: process.cwd() }); page = await app.firstWindow(); await page.waitForLoadState('domcontentloaded'); await expect(page).toHaveTitle(/BotBrowser Control/i); });
test.afterEach(async () => { if (app) await app.close(); app = null; });
test('starts main window and preload contract', async () => { const api = await page.evaluate(() => ({ platform: window.api.platform, profiles: Object.keys(window.api.profiles), browser: Object.keys(window.api.browser), kernel: Object.keys(window.api.kernel) })); expect(api.platform).toBeTruthy(); expect(api.profiles).toEqual(expect.arrayContaining(['getAll', 'create', 'update', 'delete'])); expect(api.browser).toEqual(expect.arrayContaining(['launch', 'stop', 'getRunning'])); expect(api.kernel).toEqual(expect.arrayContaining(['getCachedReleases', 'listInstalled'])); });
test('profile CRUD persists through store', async () => { const r = await page.evaluate(async () => { const p = await window.api.profiles.create({ name: 'Playwright baseline', cookies: '[{"name":"sid","value":"fixture"}]' }); const u = await window.api.profiles.update(p.id, { proxyServer: 'http://127.0.0.1:8080' }); const all = await window.api.profiles.getAll(); await window.api.profiles.delete(p.id); return { p, u, all }; }); expect(r.p.name).toBe('Playwright baseline'); expect(r.u.proxyServer).toBe('http://127.0.0.1:8080'); expect(r.all.some(p => p.id === r.p.id)).toBeTruthy(); });
test('settings and proxy validation IPC are observable', async () => { const r = await page.evaluate(async () => { const old = await window.api.settings.get(); await window.api.settings.set({ defaultProxy: 'http://127.0.0.1:9' }); const s = await window.api.settings.get(); let error = ''; try { await window.api.proxy.checkIp('not-a-proxy'); } catch (e) { error = e.message; } await window.api.settings.set({ defaultProxy: old.defaultProxy }); return { s, error }; }); expect(r.s.defaultProxy).toBe('http://127.0.0.1:9'); expect(r.error).toMatch(/invalid proxy|ENOTFOUND|proxy/i); });
test('kernel cache and installed-list boundaries are readable without real kernel', async () => { const r = await page.evaluate(async () => ({ cached: await window.api.kernel.getCachedReleases(), installed: await window.api.kernel.listInstalled(), dir: await window.api.kernel.getDir() })); expect(Array.isArray(r.cached) || r.cached === null).toBeTruthy(); expect(Array.isArray(r.installed)).toBeTruthy(); expect(r.dir).toBeTruthy(); });
test('launch boundary reports missing BotBrowser executable', async () => { const error = await page.evaluate(async () => { const p = await window.api.profiles.create({ name: 'Launch boundary', cookies: '[{"name":"sid","value":"fixture"}]' }); let e = ''; try { await window.api.browser.launch(p.id); } catch (x) { e = x.message; } await window.api.profiles.delete(p.id); return e; }); expect(error).toMatch(/executable not found/i); });
test('update check failure or result is observable', async () => { const r = await page.evaluate(async () => { try { return { ok: true, value: await window.api.app.checkForUpdates() }; } catch (e) { return { ok: false, error: e.message }; } }); expect(r.ok === true || typeof r.error === 'string').toBeTruthy(); });


